// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/popcorn/log4j/PopcornPacket.proto

package org.popcorn.log4j;

public final class PopcornProtos {
  private PopcornProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PopcornPacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 packetV = 1;
    boolean hasPacketV();
    int getPacketV();
    
    // required string node = 2;
    boolean hasNode();
    String getNode();
    
    // required string role = 3;
    boolean hasRole();
    String getRole();
    
    // required string version = 4;
    boolean hasVersion();
    String getVersion();
    
    // required uint32 level = 5;
    boolean hasLevel();
    int getLevel();
    
    // required string message = 6;
    boolean hasMessage();
    String getMessage();
    
    // required string module = 7;
    boolean hasModule();
    String getModule();
    
    // required string funcName = 8;
    boolean hasFuncName();
    String getFuncName();
    
    // required string line = 9;
    boolean hasLine();
    String getLine();
    
    // optional string pid = 10;
    boolean hasPid();
    String getPid();
  }
  public static final class PopcornPacket extends
      com.google.protobuf.GeneratedMessage
      implements PopcornPacketOrBuilder {
    // Use PopcornPacket.newBuilder() to construct.
    private PopcornPacket(Builder builder) {
      super(builder);
    }
    private PopcornPacket(boolean noInit) {}
    
    private static final PopcornPacket defaultInstance;
    public static PopcornPacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public PopcornPacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.popcorn.log4j.PopcornProtos.internal_static_org_popcorn_log4j_PopcornPacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.popcorn.log4j.PopcornProtos.internal_static_org_popcorn_log4j_PopcornPacket_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 packetV = 1;
    public static final int PACKETV_FIELD_NUMBER = 1;
    private int packetV_;
    public boolean hasPacketV() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPacketV() {
      return packetV_;
    }
    
    // required string node = 2;
    public static final int NODE_FIELD_NUMBER = 2;
    private java.lang.Object node_;
    public boolean hasNode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNode() {
      java.lang.Object ref = node_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          node_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string role = 3;
    public static final int ROLE_FIELD_NUMBER = 3;
    private java.lang.Object role_;
    public boolean hasRole() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getRole() {
      java.lang.Object ref = role_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          role_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoleBytes() {
      java.lang.Object ref = role_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string version = 4;
    public static final int VERSION_FIELD_NUMBER = 4;
    private java.lang.Object version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          version_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 level = 5;
    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getLevel() {
      return level_;
    }
    
    // required string message = 6;
    public static final int MESSAGE_FIELD_NUMBER = 6;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string module = 7;
    public static final int MODULE_FIELD_NUMBER = 7;
    private java.lang.Object module_;
    public boolean hasModule() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getModule() {
      java.lang.Object ref = module_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          module_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string funcName = 8;
    public static final int FUNCNAME_FIELD_NUMBER = 8;
    private java.lang.Object funcName_;
    public boolean hasFuncName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getFuncName() {
      java.lang.Object ref = funcName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          funcName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFuncNameBytes() {
      java.lang.Object ref = funcName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        funcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string line = 9;
    public static final int LINE_FIELD_NUMBER = 9;
    private java.lang.Object line_;
    public boolean hasLine() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getLine() {
      java.lang.Object ref = line_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          line_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLineBytes() {
      java.lang.Object ref = line_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        line_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pid = 10;
    public static final int PID_FIELD_NUMBER = 10;
    private java.lang.Object pid_;
    public boolean hasPid() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getPid() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPidBytes() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      packetV_ = 0;
      node_ = "";
      role_ = "";
      version_ = "";
      level_ = 0;
      message_ = "";
      module_ = "";
      funcName_ = "";
      line_ = "";
      pid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPacketV()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRole()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModule()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuncName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLine()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, packetV_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRoleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getVersionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMessageBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getModuleBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getFuncNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getLineBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, packetV_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRoleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getVersionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMessageBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getModuleBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getFuncNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLineBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.popcorn.log4j.PopcornProtos.PopcornPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.popcorn.log4j.PopcornProtos.PopcornPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.popcorn.log4j.PopcornProtos.PopcornPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.popcorn.log4j.PopcornProtos.internal_static_org_popcorn_log4j_PopcornPacket_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.popcorn.log4j.PopcornProtos.internal_static_org_popcorn_log4j_PopcornPacket_fieldAccessorTable;
      }
      
      // Construct using org.popcorn.log4j.PopcornProtos.PopcornPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        packetV_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        node_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        role_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        module_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        funcName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        line_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        pid_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.popcorn.log4j.PopcornProtos.PopcornPacket.getDescriptor();
      }
      
      public org.popcorn.log4j.PopcornProtos.PopcornPacket getDefaultInstanceForType() {
        return org.popcorn.log4j.PopcornProtos.PopcornPacket.getDefaultInstance();
      }
      
      public org.popcorn.log4j.PopcornProtos.PopcornPacket build() {
        org.popcorn.log4j.PopcornProtos.PopcornPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.popcorn.log4j.PopcornProtos.PopcornPacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.popcorn.log4j.PopcornProtos.PopcornPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.popcorn.log4j.PopcornProtos.PopcornPacket buildPartial() {
        org.popcorn.log4j.PopcornProtos.PopcornPacket result = new org.popcorn.log4j.PopcornProtos.PopcornPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packetV_ = packetV_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.node_ = node_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.role_ = role_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.funcName_ = funcName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.line_ = line_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.popcorn.log4j.PopcornProtos.PopcornPacket) {
          return mergeFrom((org.popcorn.log4j.PopcornProtos.PopcornPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.popcorn.log4j.PopcornProtos.PopcornPacket other) {
        if (other == org.popcorn.log4j.PopcornProtos.PopcornPacket.getDefaultInstance()) return this;
        if (other.hasPacketV()) {
          setPacketV(other.getPacketV());
        }
        if (other.hasNode()) {
          setNode(other.getNode());
        }
        if (other.hasRole()) {
          setRole(other.getRole());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasFuncName()) {
          setFuncName(other.getFuncName());
        }
        if (other.hasLine()) {
          setLine(other.getLine());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPacketV()) {
          
          return false;
        }
        if (!hasNode()) {
          
          return false;
        }
        if (!hasRole()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        if (!hasModule()) {
          
          return false;
        }
        if (!hasFuncName()) {
          
          return false;
        }
        if (!hasLine()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packetV_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              node_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              role_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              version_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readUInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              message_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              module_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              funcName_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              line_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              pid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 packetV = 1;
      private int packetV_ ;
      public boolean hasPacketV() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPacketV() {
        return packetV_;
      }
      public Builder setPacketV(int value) {
        bitField0_ |= 0x00000001;
        packetV_ = value;
        onChanged();
        return this;
      }
      public Builder clearPacketV() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetV_ = 0;
        onChanged();
        return this;
      }
      
      // required string node = 2;
      private java.lang.Object node_ = "";
      public boolean hasNode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNode() {
        java.lang.Object ref = node_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          node_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        node_ = value;
        onChanged();
        return this;
      }
      public Builder clearNode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        node_ = getDefaultInstance().getNode();
        onChanged();
        return this;
      }
      void setNode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        node_ = value;
        onChanged();
      }
      
      // required string role = 3;
      private java.lang.Object role_ = "";
      public boolean hasRole() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getRole() {
        java.lang.Object ref = role_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          role_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRole(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        role_ = value;
        onChanged();
        return this;
      }
      public Builder clearRole() {
        bitField0_ = (bitField0_ & ~0x00000004);
        role_ = getDefaultInstance().getRole();
        onChanged();
        return this;
      }
      void setRole(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        role_ = value;
        onChanged();
      }
      
      // required string version = 4;
      private java.lang.Object version_ = "";
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVersion(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      void setVersion(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        version_ = value;
        onChanged();
      }
      
      // required uint32 level = 5;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // required string message = 6;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        message_ = value;
        onChanged();
      }
      
      // required string module = 7;
      private java.lang.Object module_ = "";
      public boolean hasModule() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getModule() {
        java.lang.Object ref = module_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          module_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setModule(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        module_ = value;
        onChanged();
        return this;
      }
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000040);
        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      void setModule(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        module_ = value;
        onChanged();
      }
      
      // required string funcName = 8;
      private java.lang.Object funcName_ = "";
      public boolean hasFuncName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getFuncName() {
        java.lang.Object ref = funcName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          funcName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFuncName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        funcName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFuncName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        funcName_ = getDefaultInstance().getFuncName();
        onChanged();
        return this;
      }
      void setFuncName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        funcName_ = value;
        onChanged();
      }
      
      // required string line = 9;
      private java.lang.Object line_ = "";
      public boolean hasLine() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getLine() {
        java.lang.Object ref = line_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          line_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLine(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        line_ = value;
        onChanged();
        return this;
      }
      public Builder clearLine() {
        bitField0_ = (bitField0_ & ~0x00000100);
        line_ = getDefaultInstance().getLine();
        onChanged();
        return this;
      }
      void setLine(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        line_ = value;
        onChanged();
      }
      
      // optional string pid = 10;
      private java.lang.Object pid_ = "";
      public boolean hasPid() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getPid() {
        java.lang.Object ref = pid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        pid_ = value;
        onChanged();
        return this;
      }
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000200);
        pid_ = getDefaultInstance().getPid();
        onChanged();
        return this;
      }
      void setPid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        pid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.popcorn.log4j.PopcornPacket)
    }
    
    static {
      defaultInstance = new PopcornPacket(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.popcorn.log4j.PopcornPacket)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_popcorn_log4j_PopcornPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_popcorn_log4j_PopcornPacket_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%org/popcorn/log4j/PopcornPacket.proto\022" +
      "\021org.popcorn.log4j\"\252\001\n\rPopcornPacket\022\017\n\007" +
      "packetV\030\001 \002(\r\022\014\n\004node\030\002 \002(\t\022\014\n\004role\030\003 \002(" +
      "\t\022\017\n\007version\030\004 \002(\t\022\r\n\005level\030\005 \002(\r\022\017\n\007mes" +
      "sage\030\006 \002(\t\022\016\n\006module\030\007 \002(\t\022\020\n\010funcName\030\010" +
      " \002(\t\022\014\n\004line\030\t \002(\t\022\013\n\003pid\030\n \001(\tB\"\n\021org.p" +
      "opcorn.log4jB\rPopcornProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_popcorn_log4j_PopcornPacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_popcorn_log4j_PopcornPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_popcorn_log4j_PopcornPacket_descriptor,
              new java.lang.String[] { "PacketV", "Node", "Role", "Version", "Level", "Message", "Module", "FuncName", "Line", "Pid", },
              org.popcorn.log4j.PopcornProtos.PopcornPacket.class,
              org.popcorn.log4j.PopcornProtos.PopcornPacket.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
